### ISSUE TITLE
Error when get article

### ISSUE THREAD

**Issue by cristophermarcon** [jpalmieri/zendesk_help_center_scripts#2]
Hi J,
I need some help with your code, i set all gem and when i try to execute hc_importer.rb i have this error:
C:\Users\Cristopher\zendesk_help_center_scripts\scripts>ruby hc_importer.rb
Importing category Portali e Siti Web...
Done.
Importing IT translation for category Portali e Siti Web...
Done.
Importing section Internet Browsers...
Done.
Importing IT translation for Internet Browsers...
Done.
C:/Users/Cristopher/zendesk_help_center_scripts/zd_wrapper/zd_http.rb:24:in `get': undefined method `each' for 1:Integer (NoMethodError)
        from hc_importer.rb:53:in `block (2 levels) in <main>'
        from hc_importer.rb:33:in `each'
        from hc_importer.rb:33:in `block in <main>'
        from hc_importer.rb:11:in `each'
        from hc_importer.rb:11:in `<main>'

C:\Users\Cristopher\zendesk_help_center_scripts\scripts>

Can you help me please :)
Thanks

**Comment by cristophermarcon** [comment]
Hi J,
Can you help me?
TY
